spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/Department/**
          filters:
            - name: Hystrix
              args:
               name: fallbackCommand
               fallbackuri: forward:/deptFallBack
server:
 port: 8088 
 
  
   
management:
   endpoints:
     web:
       exposure:
         include: "*"         